// src/app/docs/page.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Menu, X } from 'lucide-react'
import Footer from '@/components/Footer'
import Image from 'next/image'

export default function DocsPage() {
    const [isSidebarOpen, setIsSidebarOpen] = useState(false)

    const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen)

    return (
        <div className="min-h-screen bg-gray-900 text-white">
            <nav className="bg-gray-800 p-4 flex justify-between items-center">
                <Link href="/" className="flex items-center space-x-2">
                    <Image
                        src="/icon.png"
                        alt="GitMorph Logo"
                        width={40}
                        height={40}
                        className="rounded-full"
                    />
                    <span className="text-2xl font-bold">GitMorph</span>
                </Link>
                <button onClick={toggleSidebar} className="md:hidden">
                    {isSidebarOpen ? <X /> : <Menu />}
                </button>
            </nav>

            <div className="flex">
                <aside className={`bg-gray-800 w-64 p-6 h-auto overflow-auto transition-transform duration-300 ease-in-out ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0`}>
                    <h2 className="text-2xl font-bold mb-4">Documentation</h2>
                    <ul className="space-y-2">
                        <li><Link href="#installation" className="hover:text-green-500">Installation</Link></li>
                        <li><Link href="#usage" className="hover:text-green-500">Usage</Link></li>
                        <li><Link href="#git-commands" className="hover:text-green-500">Git Commands</Link></li>
                        <li><Link href="#beyond-git" className="hover:text-green-500">Beyond Git</Link></li>
                        <li><Link href="#configuration" className="hover:text-green-500">Configuration</Link></li>
                    </ul>
                </aside>

                <main className="flex-1 p-6">
                    <h1 className="text-4xl font-bold mb-6">GitMorph CLI Documentation</h1>

                    <section id="installation" className="mb-12">
                        <h2 className="text-2xl font-bold mb-4">Installation</h2>
                        <p className="mb-4">To install GitMorph CLI globally, run:</p>
                        <pre className="bg-gray-800 p-4 rounded-lg"><code>npm install -g gitmorph-cli</code></pre>
                    </section>

                    <section id="usage" className="mb-12">
                        <h2 className="text-2xl font-bold mb-4">Usage</h2>
                        <p className="mb-4">After installation, you can use the `gm` command followed by the desired operation.</p>
                    </section>

                    <section id="git-commands" className="mb-12">
                        <h2 className="text-2xl font-bold mb-4">Git Commands</h2>
                        <ul className="list-disc list-inside space-y-2">
                            <li><code>gm init</code>: Initialize a new Git repository</li>
                            <li><code>gm clone &lt;url&gt;</code>: Clone a repository</li>
                            <li><code>gm stage &lt;files&gt;</code>: Stage files</li>
                            <li><code>gm save &quot;&lt;message&gt;&quot;</code>: Commit changes</li>
                            <li><code>gm upload</code>: Push to remote</li>
                            <li><code>gm download</code>: Pull from remote</li>
                            <li><code>gm status</code>: Check status</li>
                            <li><code>gm history</code>: Check log</li>
                            <li><code>gm branch &lt;name&gt;</code>: Create a new branch</li>
                            <li><code>gm switch &lt;branch&gt;</code>: Switch to a different branch</li>
                            <li><code>gm merge &lt;branch&gt;</code>: Merge branches</li>
                            <li><code>gm delete &lt;branch&gt;</code>: Delete a branch</li>
                            <li><code>gm stash</code>: Stash changes</li>
                            <li><code>gm apply-stash</code>: Apply stashed changes</li>
                            <li><code>gm rebase &lt;branch&gt;</code>: Rebase current branch</li>
                        </ul>
                    </section>

                    <section id="beyond-git" className="mb-12">
                        <h2 className="text-2xl font-bold mb-4">Beyond Git</h2>
                        <ul className="list-disc list-inside space-y-2">
                            <li><code>gm create-ignore</code>: Create a .gitignore file with common patterns</li>
                            <li><code>gm analyze</code>: Analyze repository statistics</li>
                            <li><code>gm todo</code>: List or add TODO comments in your code</li>
                            <li><code>gm scaffold &lt;type&gt;</code>: Scaffold a basic project structure</li>
                            <li><code>gm search &lt;query&gt;</code>: Search for a string in all files</li>
                            <li><code>gm diff</code>: Show changes between commits, commit and working tree, etc</li>
                            <li><code>gm blame &lt;file&gt;</code>: Show what revision and author last modified each line of a file</li>
                            <li><code>gm hooks</code>: Manage Git hooks</li>
                            <li><code>gm lint</code>: Lint your code</li>
                            <li><code>gm benchmark &lt;command&gt;</code>: Run a simple benchmark test</li>
                            <li><code>gm dependencies</code>: Analyze project dependencies</li>
                            <li><code>gm docker</code>: Generate a basic Dockerfile for the project</li>
                            <li><code>gm test</code>: Run tests</li>
                        </ul>
                    </section>

                    <section id="configuration" className="mb-12">
                        <h2 className="text-2xl font-bold mb-4">Configuration</h2>
                        <p className="mb-4">You can configure GitMorph CLI using the <code>gm config</code> command:</p>
                        <ul className="list-disc list-inside space-y-2">
                            <li>Set a global configuration: <code>gm config -g -s key value</code></li>
                            <li>Set a local configuration: <code>gm config -l -s key value</code></li>
                            <li>View current configuration: <code>gm config -v</code></li>
                        </ul>
                    </section>
                </main>
            </div>

            <Footer />
        </div>
    )
}

// src/routes/docs/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { cubicInOut } from 'svelte/easing';
  import AnimatedNavbar from '$lib/components/AnimatedNavbar.svelte';
  import Footer from '$lib/components/Footer.svelte'

  let activeSection = 'introduction';
  let visible = false;

  const sections = [
    { id: 'introduction', title: 'Introduction' },
    { id: 'installation', title: 'Installation' },
    { id: 'commands', title: 'Commands' },
    { id: 'beyond-git', title: 'Beyond Git' },
    { id: 'configuration', title: 'Configuration' },
    { id: 'api', title: 'API' },
  ];

  onMount(() => {
    visible = true;
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          activeSection = entry.target.id;
        }
      });
    }, { threshold: 0.5 });

    document.querySelectorAll('section').forEach(section => observer.observe(section));
  });

  function scrollTo(id: string) {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }
</script>

<svelte:head>
  <title>GitMorph Documentation</title>
</svelte:head>

<AnimatedNavbar {activeSection} {scrollTo} />

<div class="flex bg-base-100 text-white pt-16">
  <aside class="w-64 h-screen sticky top-16 overflow-y-auto bg-neutral p-4 hidden lg:block">
    <nav>
      <ul>
        {#each sections as section}
          <li class="mb-2">
            <a
              href="#{section.id}"
              class="block py-2 px-4 rounded hover:bg-base-100 transition-colors duration-200"
              class:bg-base-100={activeSection === section.id}
              on:click|preventDefault={() => scrollTo(section.id)}
            >
              {section.title}
            </a>
          </li>
        {/each}
      </ul>
    </nav>
  </aside>
  <main class="flex-1 p-8">
    {#if visible}
      <section id="introduction" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h1 class="text-4xl font-bold mb-6 text-gitmorph-400">Introduction to GitMorph</h1>
        <p class="mb-4">GitMorph is a powerful CLI tool designed to simplify Git operations and enhance developer productivity. It provides intuitive alternatives to standard Git commands and additional features to streamline your workflow.</p>
      </section>

      <section id="installation" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h2 class="text-3xl font-bold mt-12 mb-6 text-gitmorph-400">Installation</h2>
        <p class="mb-4">To install GitMorph globally, run:</p>
        <pre class="bg-neutral p-4 rounded-lg mb-4">npm install -g gitmorph</pre>
      </section>

      <section id="commands" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h2 class="text-3xl font-bold mt-12 mb-6 text-gitmorph-400">Commands</h2>
        <p class="mb-4">GitMorph provides the following commands:</p>
        <ul class="list-disc list-inside mb-4">
          <li><code>gm init</code> - Initialize a new Git repository</li>
          <li><code>gm stage &lt;file&gt;</code> - Stage changes</li>
          <li><code>gm save "&lt;message&gt;"</code> - Commit changes</li>
          <li><code>gm upload</code> - Push changes to remote</li>
          <li><code>gm download</code> - Pull changes from remote</li>
        </ul>
      </section>

      <section id="beyond-git" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h2 class="text-3xl font-bold mt-12 mb-6 text-gitmorph-400">Beyond Git</h2>
        <p class="mb-4">GitMorph offers additional features beyond standard Git operations:</p>
        <ul class="list-disc list-inside mb-4">
          <li><code>gm create-ignore</code> - Create a .gitignore file with common patterns</li>
          <li><code>gm analyze</code> - Analyze repository statistics</li>
          <li><code>gm todo</code> - Manage TODO comments in your code</li>
          <li><code>gm scaffold</code> - Scaffold a basic project structure</li>
          <li><code>gm search</code> - Search for a string in all files</li>
        </ul>
      </section>

      <section id="configuration" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h2 class="text-3xl font-bold mt-12 mb-6 text-gitmorph-400">Configuration</h2>
        <p class="mb-4">GitMorph can be configured using a <code>.gitmorphrc</code> file in your home directory or project root. Example configuration:</p>
        <pre class="bg-neutral p-4 rounded-lg mb-4">
        </pre>
      </section>

      <section id="api" in:fly={{ y: 50, duration: 500, easing: cubicInOut }}>
        <h2 class="text-3xl font-bold mt-12 mb-6 text-gitmorph-400">API</h2>
        <p class="mb-4">GitMorph can also be used programmatically:</p>
        <pre class="bg-neutral p-4 rounded-lg mb-4">

await init();
await stage('.');
await save('Initial commit');
        </pre>
      </section>
    {/if}
  </main>
</div>

<Footer />

<style>
  :global(html) {
    scroll-behavior: smooth;
  }
</style>
